// Nav
export const NAV_TIME_SET = "NAV_TIME_SET";

export const NAV_ORIGIN_SET = "NAV_ORIGIN_SET";

export const NAV_DESTINATION_SET = "NAV_DESTINATION_SET";

// App
export const APP_LOADING = "APP_LOADING";

// User
export const USER_FETCHED = "USER_FETCHED";

export const USER_LOGGED_IN = "USER_LOGGED_IN";

export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

// Workspace
export const WORKSPACE_SET = "WORKSPACE_SET";

export const WORKSPACE_CLEAR = "WORKSPACE_CLEAR";

export const WORKSPACE_FETCHED = "WORKSPACE_FETCHED";

// Auth ?
export const REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";

export const FAILED_REQUEST = "AUTH_FAILED_REQUEST";

// Settings
export const LOCALE_SET = "LOCALE_SET";
export const SETTING_SET = "SETTING_SET";
export const TIMEZONE_SET = "TIMEZONE_SET";
export const TIMEFORMAT_SET = "TIMEFORMAT_SET";

// TODO: REMOVE
export const RESET_STATE = "SETTINGS_RESET_STATE";

export const REQUEST_FAILED = "SETTINGS_REQUEST_FAILED";
export const REQUEST_LOADING = "SETTINGS_REQUEST_LOADING";
export const REQUEST_SUCCESS = "SETTINGS_REQUEST_SUCCESS";
